### ISSUE TITLE
Value is not showing, when pass readOnly=true into component

### ISSUE THREAD

**Issue by sashkokrek** [abelchee/react-textarea-markdown-editor#8]
When I used component with readOnly property = true. Value is not showed. 

<img width="321" alt="Знімок екрана 2020-12-18 о 21 13 09" src="https://user-images.githubusercontent.com/9014479/102651859-ee4dfe80-4175-11eb-81c0-0645c51e7eba.png">
<img width="526" alt="Знімок екрана 2020-12-18 о 21 14 53" src="https://user-images.githubusercontent.com/9014479/102651994-176e8f00-4176-11eb-85c3-ca7534d7b39a.png">

**Comment by abelchee** [comment]
Fixed in 2.3.0
